src/beautycrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from users.views import LoginView, LogoutView, HomeView


urlpatterns = i18n_patterns(
    path('', HomeView.as_view(), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('salon/', include('salon.urls')),
    path('staffer/', include('staffer.urls')),
    path('services/', include('services.urls')),
    path('client/', include('client.urls')),
    path('timetable/', include('timetable.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/client/urls.py
from django.urls import path

from client.views import ClientList, ClientCreate, ClientUpdate, ClientDetail

app_name = "client"

urlpatterns = [
    path('salon/<int:salon_id>', ClientList.as_view(), name="list"),
    path('new/', ClientCreate.as_view(), name="new"),
    path('<int:pk>/', ClientDetail.as_view(), name="detail"),
    path('update/<int:pk>/', ClientUpdate.as_view(), name="update"),
]

src/salon/urls.py
from django.urls import path

from .views import SalonCreate, SalonUpdate, SalonContact, SalonOnline, InvoiceOnline, SalonOnlineHistory

app_name = "salon"

urlpatterns = [
    path('add/', SalonCreate.as_view(), name="add"),
    path('<int:pk>/', SalonUpdate.as_view(), name="detail"),
    path('contact', SalonContact.as_view(), name="contact"),
    path('online/<int:salon_id>', SalonOnline.as_view(), name="online"),
    path('online/history/<int:salon_id>', SalonOnlineHistory.as_view(), name="online-history"),
    path('invoice/<int:pk>', InvoiceOnline.as_view(), name="invoice")
]

src/services/urls.py
from django.urls import path

from services.views import (CategoryList, CategoryCreate, CategoryDetail, ServiceCreate,
                            SalonServices, ServiceUpdate, CategoryUpdate, CategoryDelete,
                            ServiceDelete)
from staffer.views import StafferAddService

app_name = "services"

urlpatterns = [
    path('', CategoryList.as_view(), name="list-category"),
    path('category/', CategoryCreate.as_view(), name="new-category"),
    path('category/<int:pk>', CategoryDetail.as_view(), name="category-detail"),
    path('category/update/<int:cid>', CategoryUpdate.as_view(), name="category-update"),
    path('category/delete/<int:pk>', CategoryDelete.as_view(), name="category-delete"),
    path('new/', ServiceCreate.as_view(), name="new"),
    path('salon/<int:sid>', SalonServices.as_view(), name="salon"),
    path('master', StafferAddService.as_view(), name="add-master"),
    path('update/<int:pk>', ServiceUpdate.as_view(), name="update"),
    path('delete/<int:pk>', ServiceDelete.as_view(), name="delete"),
]

src/staffer/urls.py
from django.urls import path

from staffer.views import (StafferCreate, StafferList, StafferUpdate, PositionView,
                           StafferInfoCreate, StafferDeleteService, PositionUpdate, PositionDelete, StafferDelete)

app_name = "staffer"

urlpatterns = [
    path('', StafferList.as_view(), name="list"),
    path('new/', StafferCreate.as_view(), name="new"),
    path('info/', StafferInfoCreate.as_view(), name="info"),
    path('<int:pk>/', StafferUpdate.as_view(), name="detail"),
    path('positions/', PositionView.as_view(), name="position"),
    path('service/delete/<int:pk>', StafferDeleteService.as_view(), name="del-service"),
    path('positions/<int:pk>', PositionUpdate.as_view(), name="position-update"),
    path('positions/delete/<int:pk>', PositionDelete.as_view(), name="position-delete"),
    path('delete/<int:pk>', StafferDelete.as_view(), name="delete")
]

src/client/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext as _

from salon.models import Salon

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Client(models.Model):
    UNKNOWN, MALE, WOMEN = 0, 1, 2
    GENDERS = (
        (UNKNOWN, _(u'Неизвестно')),
        (MALE, _(u'Мужской')),
        (WOMEN, _(u'Женский'))
    )

    full_name = models.CharField(
        max_length=255,
        verbose_name=_(u'Имя')
    )
    avatar = models.ImageField(
        upload_to='client',
        verbose_name=_(u'Аватар'),
        null=True,
        blank=True
    )
    avatar_thumbnail = ImageSpecField(
        source='avatar',
        processors=[ResizeToFill(100, 100)],
        format='JPEG'
    )
    phone = models.CharField(
        max_length=255,
        verbose_name=_(u'Сотовый')
    )
    email = models.CharField(
        max_length=255,
        verbose_name=_(u'Email'),
        null=True,
        blank=True
    )
    gender = models.PositiveSmallIntegerField(
        choices=GENDERS,
        default=UNKNOWN,
        verbose_name=_(u'Пол')
    )
    description = models.TextField(
        verbose_name=_(u'Комментарий'),
        null=True,
        blank=True
    )
    salon = models.ForeignKey(
        Salon,
        on_delete=models.CASCADE
    )

    def get_absolute_url(self):
        return reverse_lazy('client:detail', kwargs={'pk': self.pk})

    @property
    def avatar_url(self):
        img_url = "https://ui-avatars.com/api/?size=250&background=564FC1&color=fff&name=%s&font-size=0.4"

        if self.avatar:
            return self.avatar_thumbnail.url
        else:
            return img_url % self.full_name

    class Meta:
        verbose_name = _(u'Клиент')
        verbose_name_plural = _(u'Клиенты')

src/client/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, Count
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, UpdateView, DetailView

from client.models import Client
from timetable.models import TimeTable


class ClientList(LoginRequiredMixin, ListView):
    model = Client


class ClientCreate(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('full_name', 'avatar', 'phone', 'email', 'gender', 'description')

    def form_valid(self, form):
        client = form.save(commit=False)

        client.salon = self.request.user.salon
        client.save()

        return redirect(client.get_absolute_url())


class ClientUpdate(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ('full_name', 'avatar', 'phone', 'email', 'gender', 'description')


class ClientDetail(LoginRequiredMixin, DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client = self.get_object()

        histories = TimeTable.objects.filter(client=client)
        sum_profit = histories.aggregate(profit=Sum('amount'))
        count = histories.aggregate(services=Count('service_master__service'))

        context['histories'] = histories
        context['sum_profit'] = sum_profit
        context['count'] = count

        return context

src/templates/client/client_detail.html
{% extends "main.html" %}
{% load i18n %}

{% block main-content %}
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                {% trans "Настройки" %}
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="/" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a class="m-nav__link">
                        <span class="m-nav__link-text">
                            {% trans "Настройки" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'client:list' request.user.salon.pk %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Клиентская база" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'client:detail' object.pk %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {{ object.full_name }}
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="m-content">
    <div class="row">
        <div class="col-xl-3 col-lg-4">
            <div class="m-portlet m-portlet--full-height  ">
                <div class="m-portlet__body">
                    <div class="m-card-profile">
                        <div class="m-card-profile__title m--hide">
                            {{ object.full_name }}
                        </div>
                        <div class="m-card-profile__pic">
                            <div class="m-card-profile__pic-wrapper">   
                                <img src="{{ object.avatar_url }}" alt="">
                            </div>
                        </div>
                        <div class="m-card-profile__details">
                            <span class="m-card-profile__name">{{ object.full_name }}</span>
                            <a href="call:{{ object.phone }}" class="m-card-profile__email m-link">{{ object.phone }}</a>
                            {% if object.email %}
                            <a href="mailto:{{ object.email }}" class="m-card-profile__email m-link">{{ object.email }}</a>
                            {% endif %}
                        </div>
                    </div>  
                    <div class="m-portlet__body-separator"></div>
                    <div class="m-widget1 m-widget1--paddingless">
                        <div class="m-widget1__item">
                            <div class="row m-row--no-padding align-items-center">
                                <div class="col">
                                    <h3 class="m-widget1__title">{% trans "Прибыль" %}</h3>
                                    <span class="m-widget1__desc">{% trans "Сумма всех услуг" %}</span>
                                </div>
                                <div class="col m--align-right">
                                    <span class="m-widget1__number m--font-brand">
                                        +{% if sum_profit %} {{ sum_profit.profit }}₸{% endif%}
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="m-widget1__item">
                            <div class="row m-row--no-padding align-items-center">
                                <div class="col">
                                    <h3 class="m-widget1__title">{% trans "Услуги" %}</h3>
                                    <span class="m-widget1__desc">{% trans "Кол. оказ. услуг" %}</span>
                                </div>
                                <div class="col m--align-right">
                                    <span class="m-widget1__number m--font-brand">
                                        {% if count %} {{ count.services }} {% endif%}
                                    </span>
                                </div>
                            </div>
                        </div> 
                    </div>
                </div>          
            </div>  
        </div>
        <div class="col-xl-9 col-lg-8">
            <div class="m-portlet m-portlet--full-height m-portlet--tabs">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-tools">
                        <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
                            <li class="nav-item m-tabs__item">
                                <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_client_history" role="tab">
                                    <i class="flaticon-share m--hide"></i>
                                    {% trans "История посещений" %}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="m-portlet__body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="m_client_history">
                            <table class="m-datatable" >
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>{% trans "Услуга" %}</th>
                                        <th>{% trans "Мастер" %}</th>
                                        <th>{% trans "Время сеанса" %}</th>
                                        <th>{% trans "Сумма" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for history in histories %}
                                        <tr>
                                            <td>{{ history.id }}</td>
                                            <td>
                                                <a href="{% url 'services:update' history.service_master.service.id %}">
                                                    {% if request.LANGUAGE_CODE == 'kk' %}
                                                        {{ history.service_master.service.title_kz }}
                                                    {% else %}
                                                        {{ history.service_master.service.title_ru }}
                                                    {% endif %}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'staffer:detail' history.service_master.master.id %}">
                                                    {{ history.service_master.master.full_name }}
                                                </a>
                                            </td>
                                            <td>{{ history.start|date:"d.m.Y H:i" }} - {{ history.end|date:"d.m.Y H:i" }}</td>
                                            <td>{{ history.amount }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/client/client_form.html
{% extends "main.html" %}
{% load i18n bootstrap4 %}

{% block main-content %}
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                {% trans "Настройки" %}
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="/" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a class="m-nav__link">
                        <span class="m-nav__link-text">
                            {% trans "Настройки" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'client:list' request.user.salon.pk %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Клиентская база" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'client:new' %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Добавить клиента" %}
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="m-content">
    <div class="row">
        <div class="col-xl-12">
            <div class="m-portlet m-portlet--tabs">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                {% trans "Добавить клиента" %}
                            </h3>
                        </div>          
                    </div>
                    <div class="m-portlet__head-tools">
                        <ul class="nav nav-tabs m-tabs m-tabs-line  m-tabs-line--right m-tabs-line-danger" role="tablist">
                            <li class="nav-item m-tabs__item">
                                <a class="nav-link m-tabs__link active show" data-toggle="tab" href="#m_portlet_tab_1_1" role="tab" aria-selected="true">
                                    {% trans "Информация" %}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="m-portlet__body">
                    <div class="tab-content">
                        <div class="tab-pane active show" id="m_portlet_tab_1_1">
                            <form class="m-form m-form--fit m-form--label-align-right" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                {% bootstrap_form_errors form type='non_fields' %}
                                {% bootstrap_form form %}

                                <button class="btn btn-primary" type="submit">
                                    {% trans "Отправить" %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/client/client_list.html
{% extends "main.html" %}
{% load i18n %}

{% block main-content %}
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                {% trans "Настройки" %}
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="/" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a class="m-nav__link">
                        <span class="m-nav__link-text">
                            {% trans "Настройки" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'client:list' request.user.salon.pk %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Клиентская база" %}
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="m-content">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        {% trans "Клиентская база" %}
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">

            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1">
                        <div class="form-group m-form__group row align-items-center">
                            <div class="col-md-4">
                                <div class="m-input-icon m-input-icon--left">
                                    <input  type="text"
                                            class="form-control m-input"
                                            placeholder="{% trans 'Поиск' %}..."
                                            id="generalSearch">
                                    <span class="m-input-icon__icon m-input-icon__icon--left">
                                        <span>
                                            <i class="la la-search"></i>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                        <a href="{% url 'client:new' %}" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                            <span>
                                <i class="la la-plus"></i>
                                <span>
                                    {% trans "Добавить клиента" %}
                                </span>
                            </span>
                        </a>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>
            
            <table class="m-datatable staffer-datatable" width="100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{% trans "Имя" %}</th>
                        <th>{% trans "Сотовый" %}</th>
                        <th>{% trans "Email" %}</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    {% for client in object_list %}
                    <tr>
                        <td>{{ client.id }}</td>
                        <td>
                            <a href="{% url 'client:detail' client.id %}">
                                {{ client.full_name }}
                            </a>
                        </td>
                        <td>{{ client.phone }}</td>
                        <td>{{ client.email }}</td>
                        <td>
                            <span style="overflow: visible; width: 110px;">
                                <a href="{% url 'client:update' client.id %}" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit details">
                                    <i class="la la-edit"></i>
                                </a>
                                <a href="#" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" title="Delete">
                                    <i class="la la-trash"></i>
                                </a>
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock %}