src/beautycrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from users.views import LoginView, LogoutView, HomeView


urlpatterns = i18n_patterns(
    path('', HomeView.as_view(), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('salon/', include('salon.urls')),
    path('staffer/', include('staffer.urls')),
    path('services/', include('services.urls')),
    path('client/', include('client.urls')),
    path('timetable/', include('timetable.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/client/urls.py
from django.urls import path

from client.views import ClientList, ClientCreate, ClientUpdate, ClientDetail

app_name = "client"

urlpatterns = [
    path('salon/<int:salon_id>', ClientList.as_view(), name="list"),
    path('new/', ClientCreate.as_view(), name="new"),
    path('<int:pk>/', ClientDetail.as_view(), name="detail"),
    path('update/<int:pk>/', ClientUpdate.as_view(), name="update"),
]

src/salon/urls.py
from django.urls import path

from .views import SalonCreate, SalonUpdate, SalonContact, SalonOnline, InvoiceOnline, SalonOnlineHistory

app_name = "salon"

urlpatterns = [
    path('add/', SalonCreate.as_view(), name="add"),
    path('<int:pk>/', SalonUpdate.as_view(), name="detail"),
    path('contact', SalonContact.as_view(), name="contact"),
    path('online/<int:salon_id>', SalonOnline.as_view(), name="online"),
    path('online/history/<int:salon_id>', SalonOnlineHistory.as_view(), name="online-history"),
    path('invoice/<int:pk>', InvoiceOnline.as_view(), name="invoice")
]

src/services/urls.py
from django.urls import path

from services.views import (CategoryList, CategoryCreate, CategoryDetail, ServiceCreate,
                            SalonServices, ServiceUpdate, CategoryUpdate, CategoryDelete,
                            ServiceDelete)
from staffer.views import StafferAddService

app_name = "services"

urlpatterns = [
    path('', CategoryList.as_view(), name="list-category"),
    path('category/', CategoryCreate.as_view(), name="new-category"),
    path('category/<int:pk>', CategoryDetail.as_view(), name="category-detail"),
    path('category/update/<int:cid>', CategoryUpdate.as_view(), name="category-update"),
    path('category/delete/<int:pk>', CategoryDelete.as_view(), name="category-delete"),
    path('new/', ServiceCreate.as_view(), name="new"),
    path('salon/<int:sid>', SalonServices.as_view(), name="salon"),
    path('master', StafferAddService.as_view(), name="add-master"),
    path('update/<int:pk>', ServiceUpdate.as_view(), name="update"),
    path('delete/<int:pk>', ServiceDelete.as_view(), name="delete"),
]

src/staffer/urls.py
from django.urls import path

from staffer.views import (StafferCreate, StafferList, StafferUpdate, PositionView,
                           StafferInfoCreate, StafferDeleteService, PositionUpdate, PositionDelete, StafferDelete)

app_name = "staffer"

urlpatterns = [
    path('', StafferList.as_view(), name="list"),
    path('new/', StafferCreate.as_view(), name="new"),
    path('info/', StafferInfoCreate.as_view(), name="info"),
    path('<int:pk>/', StafferUpdate.as_view(), name="detail"),
    path('positions/', PositionView.as_view(), name="position"),
    path('service/delete/<int:pk>', StafferDeleteService.as_view(), name="del-service"),
    path('positions/<int:pk>', PositionUpdate.as_view(), name="position-update"),
    path('positions/delete/<int:pk>', PositionDelete.as_view(), name="position-delete"),
    path('delete/<int:pk>', StafferDelete.as_view(), name="delete")
]

src/users/urls.py
from django.urls import path

from .views import UserCreate, UserProfile, PasswordChange

app_name = "user"

urlpatterns = [
    path('add/', UserCreate.as_view(), name="add"),
    path('update/<int:pk>', UserProfile.as_view(), name="update"),
    path('password/change', PasswordChange.as_view(), name="password")
]

src/templates/base.html
<!DOCTYPE html>
<html lang="ru" >
<head>
    <meta charset="utf-8" />
    <title>
        BEAUTY SALON CRM
        {% if request.user.is_authenticated %} | {{ request.user.salon.full_name }} {% endif %}
    </title>

    <meta name="description" content="Latest updates and statistic charts">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.3.0/css/iziToast.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="/static/metronic/vendors/custom/fullcalendar/fullcalendar.bundle.css" />
    <link rel="stylesheet" href="/static/metronic/vendors/base/vendors.bundle.css" />
    <link rel="stylesheet" href="/static/metronic/demo/demo6/base/style.bundle.css" />
    <link rel="stylesheet" href="/static/css/style.css" />

    <link rel="shortcut icon" href="/static/img/favicon.ico" />
</head>
<body class="m-page--fluid m--skin- m-content--skin-light2 m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-light m-aside-left--fixed m-aside-left--offcanvas m-aside-left--minimize m-brand--minimize m-footer--push m-aside--offcanvas-default"  >

    <div class="m-grid m-grid--hor m-grid--root m-page">
        {% block content %}{% endblock %}
    </div>

    <script src="/static/metronic/vendors/base/vendors.bundle.js"></script>
    <script src="/static/metronic/demo/demo6/base/scripts.bundle.js"></script>
    <script src="/static/js/fullcalendar/fullcalendar.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.3.0/js/iziToast.min.js"></script>
    
    {% if request.LANGUAGE_CODE == 'kk' %}
    <script src="/static/js/fullcalendar/locale/kk.js"></script>
    <script src="/static/js/bootstrap-datetimepicker.kk.js"></script>
    {% else %}
    <script src="/static/js/fullcalendar/locale/ru.js"></script>
    <script src="/static/js/bootstrap-datetimepicker.ru.js"></script>
    {% endif %}

    <script src="/static/js/jquery.inputmask.bundle.js"></script>
    <script src="/static/js/bootstrap-datetimepicker.ru.js"></script>
    <script src="/static/js/app.js"></script>

</body>
</html>

src/templates/main.html
{% extends "base.html" %}
{% load i18n bootstrap4 %}

{% block content %}
<header class="m-grid__item m-header "  data-minimize-offset="200" data-minimize-mobile-offset="200" >
	<div class="m-container m-container--fluid m-container--full-height">
		<div class="m-stack m-stack--ver m-stack--desktop">
			<div class="m-stack__item m-brand  m-brand--skin-light ">
				<div class="m-stack m-stack--ver m-stack--general">
					<div class="m-stack__item m-stack__item--middle m-brand__logo">
						<a href="/" class="m-brand__logo-wrapper">
							<img alt="" src="/static/metronic/demo/demo6/media/img/logo/logo.png"/>
						</a>
						<h3 class="m-header__title">
							{{ request.user.salon.full_name }}
						</h3>
					</div>
					<div class="m-stack__item m-stack__item--middle m-brand__tools">
						<a href="javascript:;" id="m_aside_left_offcanvas_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-tablet-and-mobile-inline-block">
							<span></span>
						</a>
						<a id="m_aside_header_topbar_mobile_toggle" href="javascript:;" class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
							<i class="flaticon-more"></i>
						</a>
					</div>
				</div>
			</div>
			
			<div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav">
				<div class="m-header__title">
					<h3 class="m-header__title-text">
						{{ request.user.salon.full_name }} BS CRM
					</h3>
				</div>
				<button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-light " id="m_aside_header_menu_mobile_close_btn">
					<i class="la la-close"></i>
				</button>

				<div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">
					<div class="m-stack__item m-topbar__nav-wrapper">
						<ul class="m-topbar__nav m-nav m-nav--inline">
							<li class="m-nav__item m-topbar__quick-actions m-dropdown m-dropdown--skin-light m-dropdown--large m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push m-dropdown--mobile-full-width m-dropdown--skin-light"  data-dropdown-toggle="click">
								<a href="#" class="m-nav__link m-dropdown__toggle">
									<span class="m-nav__link-badge m-badge m-badge--dot m-badge--info m--hide"></span>
									<span class="m-nav__link-icon">
										<span class="m-nav__link-icon-wrapper">
											<i class="la la-language"></i>
										</span>
									</span>
								</a>

								<div class="m-dropdown__wrapper">
									<span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
									<div class="m-dropdown__inner">
										<div class="m-dropdown__body m-dropdown__body--paddingless">
											<div class="m-dropdown__content">
												<div class="m-scrollable" data-scrollable="false" data-max-height="380" data-mobile-max-height="200">
													<div class="m-nav-grid m-nav-grid--skin-light">
														<div class="m-nav-grid__row">
															{% get_current_language as LANGUAGE_CODE %}
															{% get_available_languages as LANGUAGES %}
													        {% get_language_info_list for LANGUAGES as languages %}
													        {% for language in languages %}
																<a href="#" class="m-nav-grid__item language-item" data-lang="{{ language.code }}">
																	<i class="m-nav-grid__icon flag-icon flag-icon-{% if language.code == 'kk' %}kz{% else %}{{ language.code }}{% endif%}"></i>
																	<span class="m-nav-grid__text">
																		{{ language.name_local }} ({{ language.code }})
																	</span>
																</a>
															{% endfor %}
														</div>
														<form action="{% url 'set_language' %}" method="post" id="set_language_form">
														    {% csrf_token %}
															<input name="language" type="hidden" value="{{ LANGUAGE_CODE }}" />
														</form>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="m-nav__item m-topbar__user-profile  m-dropdown m-dropdown--medium m-dropdown--arrow  m-dropdown--align-right m-dropdown--mobile-full-width m-dropdown--skin-light" data-dropdown-toggle="click">
								<a href="#" class="m-nav__link m-dropdown__toggle" title="{% trans "Профиль" %}">
									<span class="m-topbar__userpic m--hide">
										<img src="{{ request.user.avatar_url }}" class="m--img-rounded m--marginless m--img-centered" alt=""/>
									</span>
									<span class="m-nav__link-icon m-topbar__usericon">
										<span class="m-nav__link-icon-wrapper">
											<i class="flaticon-user-ok"></i>
										</span>
									</span>
									<span class="m-topbar__username m--hide">
										{{ request.user.full_name }}
									</span>
								</a>
								<div class="m-dropdown__wrapper">
									<span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
									<div class="m-dropdown__inner">
										<div class="m-dropdown__header m--align-center">
											<div class="m-card-user m-card-user--skin-light">
												<div class="m-card-user__pic">
													<img src="{{ request.user.avatar_url }}" class="m--img-rounded m--marginless" alt=""/>
												</div>
												<div class="m-card-user__details">
													<span class="m-card-user__name m--font-weight-500">
														{{ request.user.full_name }}
													</span>
													<a href="" class="m-card-user__email m--font-weight-300 m-link">
														{{ request.user.email }}
													</a>
												</div>
											</div>
										</div>
										<div class="m-dropdown__body">
											<div class="m-dropdown__content">
												<ul class="m-nav m-nav--skin-light">
													<li class="m-nav__section m--hide">
														<span class="m-nav__section-text">
															{% trans "Профиль" %}
														</span>
													</li>
													<li class="m-nav__item">
														<a href="{% url 'user:update' request.user.pk %}" class="m-nav__link">
															<i class="m-nav__link-icon flaticon-share"></i>
															<span class="m-nav__link-text">
																{% trans "Профиль" %}
															</span>
														</a>
													</li>
													<li class="m-nav__separator m-nav__separator--fit"></li>
													<li class="m-nav__item">
														<a href="{% url 'logout' %}" class="btn m-btn--pill    btn-secondary m-btn m-btn--custom m-btn--label-brand m-btn--bolder">
															{% trans "Выход" %}
														</a>
													</li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="m-nav__item">
								<a href="{% url 'logout' %}" class="m-nav__link" title="{% trans "Выход" %}">
									<span class="m-nav__link-icon m-nav__link-icon-alt">
										<span class="m-nav__link-icon-wrapper">
											<i class="flaticon-logout"></i>
										</span>
									</span>
								</a>
							</li>
						</ul>
					</div>
				</div>

			</div>
		</div>
	</div>
</header>

<div class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body">
	<button class="m-aside-left-close  m-aside-left-close--skin-light " id="m_aside_left_close_btn">
		<i class="la la-close"></i>
	</button>
	<div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-light ">
		<div 
			id="m_ver_menu" 
			class="m-aside-menu  m-aside-menu--skin-light m-aside-menu--submenu-skin-light " 
			data-menu-vertical="true"
			 data-menu-scrollable="true" data-menu-dropdown-timeout="500"  
			>
			<ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
				<li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true"  data-menu-submenu-toggle="hover">
					<a href="#" class="m-menu__link m-menu__toggle">
						<i class="m-menu__link-icon flaticon-app"></i>
						<span class="m-menu__link-text">
							Beauty Salon CRM
						</span>
						<i class="m-menu__ver-arrow la la-angle-right"></i>
					</a>
					<div class="m-menu__submenu ">
						<span class="m-menu__arrow"></span>
						<ul class="m-menu__subnav">
							<li class="m-menu__item  m-menu__item--parent" aria-haspopup="true" >
								<span class="m-menu__link">
									<span class="m-menu__link-text">
										{{ request.user.salon.full_name }}
									</span>
								</span>
							</li>
							<li class="m-menu__item " aria-haspopup="true"  data-redirect="true">
								<a  href="/" class="m-menu__link ">
									<i class="m-menu__link-bullet m-menu__link-bullet--dot">
										<span></span>
									</i>
									<span class="m-menu__link-text">
										{% trans "Главный" %}
									</span>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true"  data-menu-submenu-toggle="hover">
					<a  href="#" class="m-menu__link m-menu__toggle">
						<i class="m-menu__link-icon flaticon-user"></i>
						<span class="m-menu__link-text">
							{% trans "Сотрудники" %}
						</span>
						<i class="m-menu__ver-arrow la la-angle-right"></i>
					</a>
					<div class="m-menu__submenu ">
						<span class="m-menu__arrow"></span>
						<ul class="m-menu__subnav">
							<li class="m-menu__item  m-menu__item--parent" aria-haspopup="true" >
								<span class="m-menu__link">
									<span class="m-menu__link-text">
										{% trans "Сотрудники" %}
									</span>
								</span>
							</li>

							{% for staffer in request.user.salon.staffers.all %}
							<li class="m-menu__item " aria-haspopup="true"  data-redirect="true">
								<a  href="{% url 'staffer:detail' staffer.id %}" class="m-menu__link ">
									<i class="m-menu__link-bullet m-menu__link-bullet--dot">
										<span></span>
									</i>
									<span class="m-menu__link-text">
										{{ staffer.full_name }}
									</span>
								</a>
							</li>
							{% endfor %}
						</ul>
					</div>
				</li>

				<li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true"  data-menu-submenu-toggle="hover">
					<a  href="#" class="m-menu__link m-menu__toggle">
						<i class="m-menu__link-icon flaticon-settings"></i>
						<span class="m-menu__link-text">
							{% trans "Настройки" %}
						</span>
						<i class="m-menu__ver-arrow la la-angle-right"></i>
					</a>
					<div class="m-menu__submenu ">
						<span class="m-menu__arrow"></span>
						<ul class="m-menu__subnav">
							<li class="m-menu__item  m-menu__item--parent" aria-haspopup="true" >
								<span class="m-menu__link">
									<span class="m-menu__link-text">
										{% trans "Настройки" %}
									</span>
								</span>
							</li>
							<li class="m-menu__item " aria-haspopup="true"  data-redirect="true">
								<a  href="{% url 'salon:detail' request.user.salon.pk %}" class="m-menu__link ">
									<i class="m-menu__link-bullet m-menu__link-bullet--dot">
										<span></span>
									</i>
									<span class="m-menu__link-text">
										{% trans "Основные" %}
									</span>
								</a>
							</li>
							<li class="m-menu__item " aria-haspopup="true"  data-redirect="true">
								<a  href="{% url 'staffer:list' %}" class="m-menu__link ">
									<i class="m-menu__link-bullet m-menu__link-bullet--dot">
										<span></span>
									</i>
									<span class="m-menu__link-text">
										{% trans "Сотрудники" %}
									</span>
								</a>
							</li>
							<li class="m-menu__item " aria-haspopup="true"  data-redirect="true">
								<a  href="{% url 'staffer:position' %}" class="m-menu__link ">
									<i class="m-menu__link-bullet m-menu__link-bullet--dot">
										<span></span>
									</i>
									<span class="m-menu__link-text">
										{% trans "Должности" %}
									</span>
								</a>
							</li>
							<li class="m-menu__item " aria-haspopup="true"  data-redirect="true">
								<a  href="{% url 'services:list-category' %}" class="m-menu__link ">
									<i class="m-menu__link-bullet m-menu__link-bullet--dot">
										<span></span>
									</i>
									<span class="m-menu__link-text">
										{% trans "Услуги" %}
									</span>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true"  data-menu-submenu-toggle="hover">
					<a href="#" class="m-menu__link m-menu__toggle">
						<i class="m-menu__link-icon flaticon-users"></i>
						<span class="m-menu__link-text">
							{% trans "Клиенты" %}
						</span>
						<i class="m-menu__ver-arrow la la-angle-right"></i>
					</a>
					<div class="m-menu__submenu ">
						<span class="m-menu__arrow"></span>
						<ul class="m-menu__subnav">
							<li class="m-menu__item  m-menu__item--parent" aria-haspopup="true" >
								<span class="m-menu__link">
									<span class="m-menu__link-text">
										{% trans "Клиенты" %}
									</span>
								</span>
							</li>
							<li class="m-menu__item " aria-haspopup="true"  data-redirect="true">
								<a  href="{% url 'client:list' request.user.salon.pk %}" class="m-menu__link ">
									<i class="m-menu__link-bullet m-menu__link-bullet--dot">
										<span></span>
									</i>
									<span class="m-menu__link-text">
										{% trans "Клиентская база" %}
									</span>
								</a>
							</li>
						</ul>
					</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="m-grid__item m-grid__item--fluid m-wrapper">
		{% block main-content %}{% endblock %}
	</div>
</div>
{% endblock %}