src/beautycrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from users.views import LoginView, LogoutView, HomeView


urlpatterns = i18n_patterns(
    path('', HomeView.as_view(), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('salon/', include('salon.urls')),
    path('staffer/', include('staffer.urls')),
    path('services/', include('services.urls')),
    path('client/', include('client.urls')),
    path('timetable/', include('timetable.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/salon/urls.py
from django.urls import path

from .views import SalonCreate, SalonUpdate, SalonContact, SalonOnline, InvoiceOnline, SalonOnlineHistory

app_name = "salon"

urlpatterns = [
    path('add/', SalonCreate.as_view(), name="add"),
    path('<int:pk>/', SalonUpdate.as_view(), name="detail"),
    path('contact', SalonContact.as_view(), name="contact"),
    path('online/<int:salon_id>', SalonOnline.as_view(), name="online"),
    path('online/history/<int:salon_id>', SalonOnlineHistory.as_view(), name="online-history"),
    path('invoice/<int:pk>', InvoiceOnline.as_view(), name="invoice")
]

src/services/urls.py
from django.urls import path

from services.views import (CategoryList, CategoryCreate, CategoryDetail, ServiceCreate,
                            SalonServices, ServiceUpdate, CategoryUpdate, CategoryDelete,
                            ServiceDelete)
from staffer.views import StafferAddService

app_name = "services"

urlpatterns = [
    path('', CategoryList.as_view(), name="list-category"),
    path('category/', CategoryCreate.as_view(), name="new-category"),
    path('category/<int:pk>', CategoryDetail.as_view(), name="category-detail"),
    path('category/update/<int:cid>', CategoryUpdate.as_view(), name="category-update"),
    path('category/delete/<int:pk>', CategoryDelete.as_view(), name="category-delete"),
    path('new/', ServiceCreate.as_view(), name="new"),
    path('salon/<int:sid>', SalonServices.as_view(), name="salon"),
    path('master', StafferAddService.as_view(), name="add-master"),
    path('update/<int:pk>', ServiceUpdate.as_view(), name="update"),
    path('delete/<int:pk>', ServiceDelete.as_view(), name="delete"),
]

src/services/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext as _

from staffer.models import Staffer
from utils.models import CommonAbstractModel

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Category(CommonAbstractModel):
    GENERAL, MEN, WOMAN = 0, 1, 2
    GENDERS = (
        (GENERAL, _(u'Общие')),
        (MEN, _(u'Мужские')),
        (WOMAN, _(u'Женские'))
    )

    title_ru = models.CharField(
        max_length=255,
        verbose_name=_(u'Название категории RUS')
    )
    title_kz = models.CharField(
        max_length=255,
        verbose_name=_(u'Название категории KZ')
    )
    gender = models.PositiveSmallIntegerField(
        default=GENERAL,
        choices=GENDERS,
        verbose_name=_(u'Содержит услуги')
    )

    def __str__(self):
        return "%s/%s" % (self.title_kz, self.title_ru)

    class Meta:
        ordering = ['id']
        verbose_name = _(u'Категория')
        verbose_name_plural = _(u'Категории')


class Service(CommonAbstractModel):
    title_ru = models.CharField(
        max_length=255,
        verbose_name=_(u'Название услуги RUS')
    )
    title_kz = models.CharField(
        max_length=255,
        verbose_name=_(u'Название услуги KZ')
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name=_(u'Категория')
    )
    image = models.ImageField(
        upload_to='services',
        verbose_name=_(u'Изображение'),
        null=True,
        blank=True
    )
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFill(100, 100)],
        format='JPEG'
    )
    min_price = models.PositiveSmallIntegerField(
        verbose_name=_(u'Минимальная цена')
    )
    max_price = models.PositiveSmallIntegerField(
        verbose_name=_(u'Максимальная цена')
    )
    is_online = models.BooleanField(
        default=True,
        verbose_name=_(u'Онлайн-запись')
    )
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='salon_manager',
        on_delete=models.CASCADE,
    )

    def get_absolute_url(self):
        return reverse_lazy('services:category-detail', kwargs={'pk': self.category.pk})

    @property
    def logo_url(self):
        img_url = "https://ui-avatars.com/api/?size=250&background=564FC1&color=fff&name=%s&font-size=0.4"

        if self.image:
            return self.image_thumbnail.url
        else:
            return img_url % self.title_kz

    class Meta:
        ordering = ['id']
        verbose_name = _(u'Услуга')
        verbose_name_plural = _(u'Услуги')


class ServiceMasters(CommonAbstractModel):
    master = models.ForeignKey(
        Staffer,
        on_delete=models.CASCADE,
    )
    service = models.ForeignKey(
        Service,
        on_delete=models.CASCADE
    )
    duration = models.PositiveSmallIntegerField(
        verbose_name=_(u'Длительность услуги')
    )

    @property
    def duration_hours(self):
        hours = self.duration // 60
        return hours

    @property
    def duration_minutes(self):
        minutes = self.duration % 60
        return minutes

    class Meta:
        verbose_name = _(u'Услуга мастера')
        verbose_name_plural = _(u'Услуги мастеров')

src/services/views.py
from django.db.models import Count
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from salon.models import Salon
from services.models import Category, Service, ServiceMasters
from staffer.models import Staffer


class CategoryList(LoginRequiredMixin, ListView):
    model = Category


class CategoryCreate(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        try:
            title_kz = request.POST["title_kz"]
            title_ru = request.POST["title_ru"]
            gender = request.POST["gender"]

            new_category = Category(title_kz=title_kz, title_ru=title_ru, gender=gender)
            new_category.save()

            request.user.salon.service_categories.add(new_category)
            request.user.salon.save()

            return JsonResponse({"message": _("Сохранено")},
                                status=200)
        except Exception as e:
            return JsonResponse({"statusText": str(e)}, status=400)


class CategoryUpdate(LoginRequiredMixin, View):
    def post(self, request, cid, *args, **kwargs):
        try:
            category = get_object_or_404(Category, pk=cid)

            category.title_kz = request.POST["title_kz"]
            category.title_ru = request.POST["title_ru"]
            category.gender = request.POST["gender"]

            category.save()

            return JsonResponse({"message": _("Сохранено")},
                                status=200)
        except Exception as e:
            return JsonResponse({"statusText": str(e)}, status=400)


class CategoryDelete(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('services:list-category')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class CategoryDetail(LoginRequiredMixin, DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.get_object()
        context['services'] = Service.objects.filter(category=category).all()

        return context


class ServiceCreate(LoginRequiredMixin, CreateView):
    model = Service
    fields = ('title_kz', 'title_ru', 'category', 'image', 'min_price', 'max_price', 'is_online')

    def form_valid(self, form):
        service = form.save(commit=False)
        service.manager = self.request.user
        service.save()

        return redirect(service.get_absolute_url())


class ServiceUpdate(LoginRequiredMixin, UpdateView):
    model = Service
    fields = ('title_kz', 'title_ru', 'category', 'image', 'min_price', 'max_price', 'is_online')


class ServiceDelete(LoginRequiredMixin, DeleteView):
    model = Service
    success_url = reverse_lazy('services:list-category')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class SalonServices(View):

    def get(self, request, sid, *args, **kwargs):
        try:
            data = {'categories': []}
            service_filter = {}
            master_id = int(request.GET.get('m_id', 0))

            if master_id:
                service_filter = {'master_id': master_id}

            salon = get_object_or_404(Salon, pk=sid)

            for category in salon.service_categories.all():
                service_filter['service__category'] = category
                services = ServiceMasters.objects.filter(**service_filter)

                info = {
                    'id': category.id,
                    'name': category.title_kz if request.LANGUAGE_CODE == 'kk' else category.title_ru,
                    'services': []
                }

                if not master_id:
                    services = services.distinct('service')

                for service in services:
                    info['services'].append({
                        'name': service.service.title_kz if request.LANGUAGE_CODE == 'kk' else service.service.title_ru,
                        'id': service.service.id,
                        'price': (service.service.max_price + service.service.min_price) // 2,
                        'duration': '%s:%s' % (service.duration_hours, service.duration_minutes)
                    })

                if info['services']:
                    data['categories'].append(info)

            return JsonResponse(data, status=200)
        except Exception as e:
            return JsonResponse({"statusText": str(e)}, status=400)

src/templates/services/category_detail.html
{% extends "main.html" %}
{% load i18n %}

{% block main-content %}
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                {% trans "Настройки" %}
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="/" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a class="m-nav__link">
                        <span class="m-nav__link-text">
                            {% trans "Настройки" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'services:list-category' %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Категории услуг" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'services:category-detail' object.pk %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                            {% if request.LANGUAGE_CODE == 'kz' %}
                                {{ object.title_kz }}
                            {% else %}
                                {{ object.title_ru }}
                            {% endif %}
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="m-content">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        {% if request.LANGUAGE_CODE == 'kz' %}
                            {{ object.title_kz }}
                        {% else %}
                            {{ object.title_ru }}
                        {% endif %}
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1"></div>
                    <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                        <a href="{% url 'services:new' %}" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                            <span>
                                <i class="la la-plus"></i>
                                <span>
                                    {% trans "Добавить услугу" %}
                                </span>
                            </span>
                        </a>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>

            <table class="m-datatable" width="100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{% trans "Название" %}</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    {% for service in services %}
                    <tr>
                        <td>{{ service.id }}</td>
                        <td>
                            <a href="{% url 'services:update' service.id %}">
                                {% if request.LANGUAGE_CODE == 'kz' %}
                                    {{ service.title_kz }}
                                {% else %}
                                    {{ service.title_ru }}
                                {% endif %}
                            </a>
                        </td>
                        <td>
                            <span style="overflow: visible; width: 110px;">
                                <a href="{% url 'services:update' service.id %}" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit details">
                                    <i class="la la-edit"></i>
                                </a>
                                <a  href="{% url 'services:delete' service.id %}"
                                    class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill delete-obj"
                                    title="Delete"
                                    data-title="{% trans 'Вы действительно хотите удалить?' %}"
                                    data-text="{% trans 'После удаления невозможно восстановить данные.' %}"
                                    >
                                    <i class="la la-trash"></i>
                                </a>
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}

src/templates/services/category_list.html
{% extends "main.html" %}
{% load i18n %}

{% block main-content %}
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                {% trans "Настройки" %}
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="/" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a class="m-nav__link">
                        <span class="m-nav__link-text">
                            {% trans "Настройки" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'services:list-category' %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Категории услуг" %}
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="m-content">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        {% trans "Категории услуг" %}
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1"></div>
                    <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                        <button class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill" type="button" data-toggle="modal" data-target="#category_modal">
                            <span>
                                <i class="la la-plus"></i>
                                <span>
                                    {% trans "Добавить категорию" %}
                                </span>
                            </span>
                        </button>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>

            <table class="m-datatable" width="100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{% trans "Название" %}</th>
                        <th>{% trans "Содержит услуги" %}</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in request.user.salon.service_categories.all %}
                    <tr>
                        <td>{{ category.id }}</td>
                        <td>
                            <a href="{% url 'services:category-detail' category.id %}">
                                {% if request.LANGUAGE_CODE == 'kk' %}
                                    {{ category.title_kz }}
                                {% else %}
                                    {{ category.title_ru }}
                                {% endif %}
                            </a>
                        </td>
                        <td>{{ category.get_gender_display }}</td>
                        <td>
                            <span style="overflow: visible; width: 110px;">
                                <a  href="#"
                                    class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill category-update"
                                    title="Edit details"
                                    data-id="{{ category.id }}"
                                    data-title-kz="{{ category.title_kz }}"
                                    data-title-ru="{{ category.title_ru }}"
                                    data-gender="{{ category.gender }}"
                                    >
                                    <i class="la la-edit"></i>
                                </a>
                                <a  href="{% url 'services:category-delete' category.id %}"
                                    class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill delete-obj"
                                    title="Delete"
                                    data-title="{% trans 'Вы действительно хотите удалить?' %}"
                                    data-text="{% trans 'После удаления невозможно восстановить данные.' %}"
                                    >
                                    <i class="la la-trash"></i>
                                </a>
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

<div class="modal fade" id="category_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{% trans "Добавить категорию" %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="m-form m-form--label-align-right is-ajax" method="post" action="{% url 'services:new-category' %}" id="new-category-form">
                    {% csrf_token %}
                    <div class="form-group m-form__group">
                        <label for="title_kz">{% trans "Название на казахском" %}</label>
                        <input type="text" class="form-control m-input m-input--square" id="title_kz" placeholder="{% trans 'Название на казахском' %}" name="title_kz">
                    </div>
                    <div class="form-group m-form__group">
                        <label for="title_ru">{% trans "Название на русском" %}</label>
                        <input type="text" class="form-control m-input m-input--square" id="title_ru" placeholder="{% trans 'Название на русском' %}" name="title_ru">
                    </div>
                    <div class="form-group m-form__group">
                        <label for="gender">{% trans "Содержит услуги" %}</label>
                        <select class="form-control m-input m-input--square" id="gender" name="gender">
                            <option value="0">{% trans "Общие" %}</option>
                            <option value="1">{% trans "Мужские" %}</option>
                            <option value="2">{% trans "Женские" %}</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">{% trans "Отправить" %}</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Отмена" %}</button>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/services/service_form.html
{% extends "main.html" %}
{% load i18n bootstrap4 %}

{% block main-content %}
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                {% trans "Настройки" %}
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="/" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a class="m-nav__link">
                        <span class="m-nav__link-text">
                            {% trans "Настройки" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'services:list-category' %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Категория услуг" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    {% trans "Новая услуга" %}
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="m-content">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        {% trans "Новая услуга" %}
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <form class="m-form m-form--fit m-form--label-align-right" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% bootstrap_form_errors form type='non_fields' %}
                
                {% bootstrap_field form.title_kz %}
                {% bootstrap_field form.title_ru %}
                {% bootstrap_field form.image %}
                {% bootstrap_field form.min_price %}
                {% bootstrap_field form.max_price %}
                
                <div class="form-group">
                    <label for="id_category">{% trans "Категория" %}</label>
                    <select name="category" class="form-control" id="id_category" required="" title="">
                        <option value="" selected="">---------</option>

                        {% for cat in request.user.salon.service_categories.all %}
                            <option value="{{ cat.id }}" {% if object.category.id == cat.id %}selected{% endif %}>{{ cat }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% bootstrap_field form.is_online %}

                <button class="btn btn-primary" type="submit">
                    {% trans "Отправить" %}
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}