src/beautycrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from users.views import LoginView, LogoutView, HomeView


urlpatterns = i18n_patterns(
    path('', HomeView.as_view(), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('salon/', include('salon.urls')),
    path('staffer/', include('staffer.urls')),
    path('services/', include('services.urls')),
    path('client/', include('client.urls')),
    path('timetable/', include('timetable.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/salon/urls.py
from django.urls import path

from .views import SalonCreate, SalonUpdate, SalonContact, SalonOnline, InvoiceOnline, SalonOnlineHistory

app_name = "salon"

urlpatterns = [
    path('add/', SalonCreate.as_view(), name="add"),
    path('<int:pk>/', SalonUpdate.as_view(), name="detail"),
    path('contact', SalonContact.as_view(), name="contact"),
    path('online/<int:salon_id>', SalonOnline.as_view(), name="online"),
    path('online/history/<int:salon_id>', SalonOnlineHistory.as_view(), name="online-history"),
    path('invoice/<int:pk>', InvoiceOnline.as_view(), name="invoice")
]

src/services/urls.py
from django.urls import path

from services.views import (CategoryList, CategoryCreate, CategoryDetail, ServiceCreate,
                            SalonServices, ServiceUpdate, CategoryUpdate, CategoryDelete,
                            ServiceDelete)
from staffer.views import StafferAddService

app_name = "services"

urlpatterns = [
    path('', CategoryList.as_view(), name="list-category"),
    path('category/', CategoryCreate.as_view(), name="new-category"),
    path('category/<int:pk>', CategoryDetail.as_view(), name="category-detail"),
    path('category/update/<int:cid>', CategoryUpdate.as_view(), name="category-update"),
    path('category/delete/<int:pk>', CategoryDelete.as_view(), name="category-delete"),
    path('new/', ServiceCreate.as_view(), name="new"),
    path('salon/<int:sid>', SalonServices.as_view(), name="salon"),
    path('master', StafferAddService.as_view(), name="add-master"),
    path('update/<int:pk>', ServiceUpdate.as_view(), name="update"),
    path('delete/<int:pk>', ServiceDelete.as_view(), name="delete"),
]

src/staffer/urls.py
from django.urls import path

from staffer.views import (StafferCreate, StafferList, StafferUpdate, PositionView,
                           StafferInfoCreate, StafferDeleteService, PositionUpdate, PositionDelete, StafferDelete)

app_name = "staffer"

urlpatterns = [
    path('', StafferList.as_view(), name="list"),
    path('new/', StafferCreate.as_view(), name="new"),
    path('info/', StafferInfoCreate.as_view(), name="info"),
    path('<int:pk>/', StafferUpdate.as_view(), name="detail"),
    path('positions/', PositionView.as_view(), name="position"),
    path('service/delete/<int:pk>', StafferDeleteService.as_view(), name="del-service"),
    path('positions/<int:pk>', PositionUpdate.as_view(), name="position-update"),
    path('positions/delete/<int:pk>', PositionDelete.as_view(), name="position-delete"),
    path('delete/<int:pk>', StafferDelete.as_view(), name="delete")
]

src/staffer/models.py
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.db import models

from utils.models import CommonAbstractModel

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Position(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name=_(u'Название')
    )
    description = models.TextField(
        verbose_name=_(u'Описание')
    )

    @staticmethod
    def get_absolute_url():
        return reverse_lazy('staffer:position')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['id']
        verbose_name = _(u'Должность')
        verbose_name_plural = _(u'Должности')


class Staffer(CommonAbstractModel):
    MASTER_FIRED = (
        (True, _(u'Уволен')),
        (False, _(u'Работает'))
    )

    full_name = models.CharField(
        max_length=255,
        verbose_name=_(u'Имя')
    )
    avatar = models.ImageField(
        upload_to='staffer',
        verbose_name=_(u'Аватар'),
        null=True,
        blank=True
    )
    avatar_thumbnail = ImageSpecField(
        source='avatar',
        processors=[ResizeToFill(100, 100)],
        format='JPEG'
    )
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        verbose_name=_(u'Должность')
    )
    specialization = models.CharField(
        max_length=255,
        verbose_name=_(u'Специализация')
    )
    master_fired = models.BooleanField(
        choices=MASTER_FIRED,
        default=False,
        verbose_name=_(u'Статус')
    )
    description = models.TextField(
        verbose_name=_(u'Описание')
    )

    def get_absolute_url(self):
        return reverse_lazy('staffer:detail', kwargs={'pk': self.pk})

    @property
    def avatar_url(self):
        img_url = "https://ui-avatars.com/api/?size=250&background=564FC1&color=fff&name=%s&font-size=0.4"

        if self.avatar:
            return self.avatar_thumbnail.url
        else:
            return img_url % self.full_name

    class Meta:
        verbose_name = _(u'Сотрудник')
        verbose_name_plural = _(u' Сотрудники')


class StafferInfo(CommonAbstractModel):
    UNKNOWN, MEN, WOMAN = 0, 1, 2
    GENDERS = (
        (UNKNOWN, _(u'Неизвестно')),
        (MEN, _(u'Мужской')),
        (WOMAN, _(u'Женский'))
    )

    staffer = models.ForeignKey(
        Staffer,
        on_delete=models.CASCADE,
        verbose_name=_(u'Сотрудник')
    )
    date_of_employment = models.DateField(
        null=True,
        blank=True,
        verbose_name=_(u'Дата приема на работу')
    )
    phone_number = models.CharField(
        null=True,
        blank=True,
        max_length=20,
        verbose_name=_(u'Номер телефона')
    )
    gender = models.PositiveSmallIntegerField(
        default=UNKNOWN,
        choices=GENDERS,
        verbose_name=_(u'Пол')
    )
    passport_data = models.TextField(
        null=True,
        blank=True,
        verbose_name=_(u'Паспортные данные')
    )
    iin = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name=_(u'ИИН')
    )

    class Meta:
        verbose_name = _(u'Дополнительная информация')
        verbose_name_plural = _(u'Дополнительные информации')

src/staffer/forms.py
from django import forms
from staffer.models import StafferInfo


class StafferInfoForm(forms.ModelForm):
    class Meta:
        fields = ('date_of_employment', 'phone_number', 'gender', 'passport_data', 'iin', 'staffer')
        model = StafferInfo
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 4, 'cols': 15})
        }

src/staffer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views import View
from django.views.generic import ListView, UpdateView, TemplateView, CreateView, DeleteView

from services.models import ServiceMasters, Service
from staffer.forms import StafferInfoForm
from staffer.models import Staffer, Position, StafferInfo


class StafferList(LoginRequiredMixin, ListView):
    model = Staffer


class StafferUpdate(LoginRequiredMixin, UpdateView):
    model = Staffer
    template_name_suffix = '_new'
    fields = ('full_name', 'avatar', 'position', 'specialization', 'master_fired', 'description')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        staffer = self.get_object()
        staffer_info_form = StafferInfoForm()
        master_services = ServiceMasters.objects.filter(master=staffer)
        services = Service.objects.filter(category__in=self.request.user.salon.service_categories.all()).exclude(pk__in=master_services.values_list('id', flat=True))

        try:
            staffer_info = StafferInfo.objects.get(staffer=staffer)
            staffer_info_form = StafferInfoForm(None, instance=staffer_info)
        except:
            pass

        context['staffer_info_form'] = staffer_info_form
        context['master_services'] = master_services
        context['services'] = services

        return context


class StafferInfoCreate(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        try:
            info_form = StafferInfoForm(request.POST or None)

            if info_form.is_valid():
                info_form.save()
            else:
                return JsonResponse({"statusText": info_form.errors.as_text() }, status=400)

            return JsonResponse({"message": _("Сохранено")},
                                status=200)
        except Exception as e:
            return JsonResponse({"statusText": str(e)}, status=400)


class StafferCreate(LoginRequiredMixin, CreateView):
    model = Staffer
    template_name_suffix = '_new'
    fields = ('full_name', 'avatar', 'position', 'specialization', 'master_fired', 'description')

    def form_valid(self, form):
        staffer = form.save()

        self.request.user.salon.staffers.add(staffer)
        self.request.user.salon.save()

        return redirect(staffer.get_absolute_url())


class PositionView(LoginRequiredMixin, TemplateView):
    template_name = 'staffer/position.html'

    def post(self, request, *args, **kwargs):
        try:
            title = request.POST["title"]
            description = request.POST["description"]

            new_position = Position(title=title, description=description)
            new_position.save()

            request.user.salon.positions.add(new_position)
            request.user.salon.save()

            return JsonResponse({"message": _("Сохранено")},
                                status=200)
        except Exception as e:
            return JsonResponse({"statusText": str(e)}, status=400)


class StafferAddService(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        try:
            service = get_object_or_404(Service, pk=request.POST['service'])
            master = get_object_or_404(Staffer, pk=request.POST['master'])
            hour, minute = request.POST['duration'].split(':')
            duration = (int(hour) * 60) + int(minute)

            new_master_service = ServiceMasters(service=service, master=master, duration=duration)
            new_master_service.save()

            return JsonResponse({"message": _("Услуга успешно добавлен для мастера.")},
                                status=200)
        except Exception as e:
            return JsonResponse({"statusText": str(e)}, status=400)


class StafferDeleteService(LoginRequiredMixin, DeleteView):
    model = ServiceMasters
    success_url = reverse_lazy('staffer:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class PositionUpdate(UpdateView):
    model = Position
    fields = ('title', 'description')


class PositionDelete(LoginRequiredMixin, DeleteView):
    model = Position
    success_url = Position.get_absolute_url()

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class StafferDelete(LoginRequiredMixin, DeleteView):
    model = Staffer
    success_url = reverse_lazy('staffer:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

src/templates/staffer/position_form.html
{% extends "main.html" %}
{% load i18n bootstrap4 %}

{% block main-content %}
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                {% trans "Настройки" %}
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="/" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a class="m-nav__link">
                        <span class="m-nav__link-text">
                            {% trans "Настройки" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'staffer:position' %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Должности" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'staffer:position-update' object.pk %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {{ object.title }}
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="m-content">
    <div class="row">
        <div class="col-xl-12">
            <div class="m-portlet m-portlet--tabs">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                {{ object.title }}
                            </h3>
                        </div>          
                    </div>
                    <div class="m-portlet__head-tools">
                        <ul class="nav nav-tabs m-tabs m-tabs-line  m-tabs-line--right m-tabs-line-danger" role="tablist">
                            <li class="nav-item m-tabs__item">
                                <a class="nav-link m-tabs__link active show" data-toggle="tab" href="#m_portlet_tab_1_1" role="tab" aria-selected="true">
                                    {% trans "Информация" %}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="m-portlet__body">
                    <div class="tab-content">
                        <div class="tab-pane active show" id="m_portlet_tab_1_1">
                            <form class="m-form m-form--fit m-form--label-align-right" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                {% bootstrap_form_errors form type='non_fields' %}
                                {% bootstrap_form form %}

                                <button class="btn btn-primary" type="submit">
                                    {% trans "Отправить" %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/staffer/staffer_new.html
{% extends "main.html" %}
{% load i18n bootstrap4 %}

{% block main-content %}
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                {% trans "Настройки" %}
            </h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="/" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a class="m-nav__link">
                        <span class="m-nav__link-text">
                            {% trans "Настройки" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                <li class="m-nav__item">
                    <a href="{% url 'staffer:list' %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Сотрудники" %}
                        </span>
                    </a>
                </li>
                <li class="m-nav__separator">
                    -
                </li>
                {% if object %}
                <li class="m-nav__item">
                    <a href="{% url 'staffer:detail' object.pk %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {{ object.full_name }}
                        </span>
                    </a>
                </li>
                {% else %}
                <li class="m-nav__item">
                    <a href="{% url 'staffer:detail' 0 %}" class="m-nav__link">
                        <span class="m-nav__link-text">
                           {% trans "Новый сотрудник" %}
                        </span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

<div class="m-content">
    <div class="row">
        <div class="col-xl-4">
            <div class="m-portlet m-portlet--full-height ">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                {% trans "Сотрудники" %}
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__body">
                    <div class="m-widget4">
                        {% for staffer in request.user.salon.staffers.all %}
                        <div class="m-widget4__item">
                            <div class="m-widget4__img m-widget4__img--pic">                             
                                <img src="{{ staffer.avatar_url }}" alt="">   
                            </div>
                            <div class="m-widget4__info">
                                <span class="m-widget4__title">
                                {{ staffer.full_name }}
                                </span><br> 
                                <span class="m-widget4__sub">
                                {{ staffer.position.title }}
                                </span>                                  
                            </div>
                            <div class="m-widget4__ext">
                                <a href="{% url 'staffer:detail' staffer.pk %}" class="m-btn m-btn--pill m-btn--hover-brand btn btn-sm btn-secondary">
                                    {% trans "Информация" %}
                                </a>
                            </div>
                        </div>
                        {% endfor %}          
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <div class="m-portlet m-portlet--tabs">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                {% if object %}
                                    {{ object.full_name }}
                                {% else %}
                                    {% trans "Новый сотрудник" %}
                                {% endif %}
                            </h3>
                        </div>          
                    </div>
                    <div class="m-portlet__head-tools">
                        <ul class="nav nav-tabs m-tabs m-tabs-line  m-tabs-line--right m-tabs-line-danger" role="tablist">
                            <li class="nav-item m-tabs__item">
                                <a class="nav-link m-tabs__link active show" data-toggle="tab" href="#m_portlet_tab_1_1" role="tab" aria-selected="true">
                                    {% trans "Информация" %}
                                </a>
                            </li>
                            <li class="nav-item m-tabs__item">
                                <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_portlet_tab_1_2" role="tab" aria-selected="false">
                                    {% trans "Доп. инфо" %}
                                </a>
                            </li>
                            <li class="nav-item m-tabs__item">
                                <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_portlet_tab_1_3" role="tab" aria-selected="false">
                                    {% trans "Услуги и длительность" %}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="m-portlet__body">
                    <div class="tab-content">
                        <div class="tab-pane active show" id="m_portlet_tab_1_1">
                            <form class="m-form m-form--fit m-form--label-align-right" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                {% bootstrap_form_errors form type='non_fields' %}
                                {% bootstrap_form form %}

                                <button class="btn btn-primary" type="submit">
                                    {% trans "Отправить" %}
                                </button>
                            </form>
                        </div>
                        <div class="tab-pane" id="m_portlet_tab_1_2">
                            {% if object %}
                            <form class="m-form m-form--fit m-form--label-align-right is-ajax" method="post" action="{% url 'staffer:info' %}">
                                <input type="hidden" name="staffer" value="{{ object.pk }}">
                                {% csrf_token %}

                                {% bootstrap_form_errors staffer_info_form type='non_fields' %}
                                
                                {% bootstrap_field staffer_info_form.date_of_employment %}
                                {% bootstrap_field staffer_info_form.phone_number %}
                                {% bootstrap_field staffer_info_form.gender %}
                                {% bootstrap_field staffer_info_form.passport_data %}
                                {% bootstrap_field staffer_info_form.iin %}

                                <button class="btn btn-primary" type="submit">
                                    {% trans "Отправить" %}
                                </button>
                            </form>
                            {% else %}
                                {% trans "Сотрудник не добавлен!" %}
                            {% endif %}
                        </div>
                        <div class="tab-pane" id="m_portlet_tab_1_3">
                            <form action="{% url 'services:add-master' %}" method="post" class="is-ajax">
                                {% csrf_token %}
                                <input type="hidden" name="master" value="{{ object.pk }}">
                                <div class="form-group m-form__group row">
                                    <div class="col-lg-6">
                                        <label>{% trans "Услуга" %}</label>
                                        <select class="form-control m-input" name="service">
                                            {% for service in services %}
                                                <option value="{{ service.id }}">
                                                    {% if request.LANGUAGE_CODE == 'kk' %}
                                                        {{ service.title_kz }}
                                                    {% else %}
                                                        {{ service.title_ru }}
                                                    {% endif %}
                                                </option>
                                            {% endfor %}
                                        </select>
                                        <span class="m-form__help">{% trans "Выберите услугу для мастера" %}</span>
                                    </div>
                                    <div class="col-lg-4">
                                        <label>{% trans "Время" %}</label>
                                        <input type="text" id="service_duration" class="form-control m-input" placeholder="{% trans 'Время' %}" name="duration">
                                        <span class="m-form__help">{% trans "Средняя длит. услуги(чч:мм)" %}</span>
                                    </div>
                                    <div class="col-lg-2">
                                        <label>&nbsp;</label>
                                        <button type="submit" class="form-control btn btn-success">{% trans "Добавить" %}</button>
                                    </div>
                                </div>
                            </form>
                            <hr>
                            <table class="table table-striped m-table">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>{% trans "Услуга" %}</th>
                                        <th>{% trans "Длительность" %}</th>
                                        <th>#</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for service in master_services %}
                                        <tr>
                                            <th scope="row">{{ service.service.id }}</th>
                                            <td>
                                                <a href="{% url 'services:update' service.service.id %}">
                                                    {% if request.LANGUAGE_CODE == 'kk' %}
                                                        {{ service.service.title_kz }}
                                                    {% else %}
                                                        {{ service.service.title_ru }}
                                                    {% endif %}
                                                </a>
                                            </td>
                                            <td>{{ service.duration_hours }}:{{ service.duration_minutes }}</td>
                                            <td>
                                                <a  href="{% url 'staffer:del-service' service.id %}"
                                                    class="m-portlet__nav-link delete-obj"
                                                    title="Delete"
                                                    data-title="{% trans 'Вы действительно хотите удалить?' %}"
                                                    data-text="{% trans 'После удаления невозможно восстановить данные.' %}"
                                                    >
                                                    <i class="la la-trash"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}